### Line Continuation

In [1]:
x = 1+2+3+\
4+5
print(x)

15


### Multiple Statements on a Single Line

In [2]:
x = 2; y = 3; z = x+y
print(z)

5


### List Comprehension

In [3]:
x = [i for i in range(10)]
print(f"x : {x}")

x : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### List Comprehension with if Condition

In [4]:
x = [i**2 for i in range(10) if i%2==0]
print(f"x : {x}")

x : [0, 4, 16, 36, 64]


### Nested List Comprehension

In [5]:
x = [(i,j) for i in range(2) for j in range(3)]
print(f"x : {x}")

x : [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)]


### Enumerate
* used to access index and element at the same time.

In [6]:
x = ["apple", "banana", "cherry", "kiwi", "orange", "watermelon"]
for i,j in enumerate(x):
    print(i, "->", j)

0 -> apple
1 -> banana
2 -> cherry
3 -> kiwi
4 -> orange
5 -> watermelon


In [7]:
x = [1,2,3,4,5]
first, *middle, last = x
print(first)
print(middle)
print(last)

1
[2, 3, 4]
5


In [8]:
x = (1,2,3,4,5)
first, *middle, last = x
print(first)
print(middle)
print(last)

1
[2, 3, 4]
5


### Copy
* If we change or modify one variable the other variable also gets updated.

In [9]:
x = [1,2,3,4,5]
y = x
x.append(10)
print(x, y)
y.append(20)
print(x,y)

[1, 2, 3, 4, 5, 10] [1, 2, 3, 4, 5, 10]
[1, 2, 3, 4, 5, 10, 20] [1, 2, 3, 4, 5, 10, 20]


### Shallow Copy

In [10]:
x = [1,2,3,4,5]
y = x.copy()
x.append(10)
print(x, y)
y.append(20)
print(x,y)

[1, 2, 3, 4, 5, 10] [1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 10] [1, 2, 3, 4, 5, 20]


### Set Comprehension

In [11]:
set(i for i in range(1,6))

{1, 2, 3, 4, 5}

### Dictionary Comprehension

In [12]:
{i:i**2 for i in range(1,11) if i%2 != 0}

{1: 1, 3: 9, 5: 25, 7: 49, 9: 81}

### Positional Arguments
* args

In [13]:
def test(*args):
    for i in args:
        print(i)
    print()

test("Sai", 24, 6.2)
test("krishna", 65.3, "White")

Sai
24
6.2

krishna
65.3
White



### keyword Arguments
* kwargs

In [14]:
def details(**kwargs):
    for i,j in kwargs.items():
        print(f"{i} : {j}")
    print()

details(name = "Sai", age = 24, height = 6.2)
details(name = "Krishna", weight = 65.3, color = "White")

name : Sai
age : 24
height : 6.2

name : Krishna
weight : 65.3
color : White



### Positional & Keyword Arguments both combined

In [15]:
def sample(*args, **kwargs):
    for i in args:
        print(f"Positional Arguments : {i}")
    print()
    for i,j in kwargs.items():
        print(f"Keyword Arguments : {i} ---> {j}")

sample(1,2,3,4, name = "Sai", age = "24", height = 6.2)

Positional Arguments : 1
Positional Arguments : 2
Positional Arguments : 3
Positional Arguments : 4

Keyword Arguments : name ---> Sai
Keyword Arguments : age ---> 24
Keyword Arguments : height ---> 6.2


### Lambda Function

In [16]:
addition = lambda a,b : a+b
addition(2,3)

5

### lambda function with condition

In [17]:
even = lambda n : n%2==0
even(7)

False

* We can't pass the list of numbers into a single parameter in a lambda function
* We can achive that with the help of map.

In [18]:
numbers = [1,2,3,4,5]
square = lambda x:x**2
# square(numbers)

### Map
* Instead of using for loop, It would be the best one.
* Map takes two inputs, 1 ---> function, 2 ---> iterable items. ex(list, tuple, set, .....)

In [19]:
numbers = [1,2,3,4,5]

def cube(num):
    return num**3

map(cube, numbers)

In [20]:
list(map(cube, numbers))

[1, 8, 27, 64, 125]

### Map with Lambda Function

In [21]:
map(lambda x:x**2, numbers)

In [22]:
tuple(map(lambda x:x**2, numbers))

(1, 4, 9, 16, 25)

### Map with multiple iterable items

In [23]:
x1 = [10,20,30]
x2 = [50,80,20]

list(map(lambda x,y : x+y, x1, x2))

[60, 100, 50]

### Real time use cases with Map

* To convert a list of strings to integers

In [24]:
str_numbers = ["1", "2", "3"]
int_numbers = list(map(int, str_numbers))
int_numbers

[1, 2, 3]

* Capitalise each word

In [25]:
words = ["apple", "banana", "cherry", "orange", "papaya"]
cap_words = list(map(str.capitalize, words))
cap_words

['Apple', 'Banana', 'Cherry', 'Orange', 'Papaya']

* get names from a dictionary

In [26]:
people = [{"name" : "Sai", "age" : 24},
          {"name" : "Krishna", "age" : 22}]

list(map(lambda x : x["name"], people))

['Sai', 'Krishna']

### Filter

In [27]:
n = [i for i in range(1,51)]

odd = list(filter(lambda x : x%2!=0, n))
print(f"Odd Numbers : {odd}")

even = list(filter(lambda x : x%2==0, n))
print(f"Even Numbers : {even}")

Odd Numbers : [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]
Even Numbers : [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


In [28]:
print(list(filter(lambda x : x>5 and x<=25 and x%2==0, n)))

[6, 8, 10, 12, 14, 16, 18, 20, 22, 24]


In [29]:
people = [{"name" : "Sai", "age" : 24},
          {"name" : "Krishna", "age" : 18},
          {"name" : "Barghav", "age" : 15},
          {"name" : "Venkateswara", "age" : 52},
          {"name" : "Cintu", "age" : 17}]

print(f"Adult : {list(filter(lambda x : x["age"]>19, people))}\n")
print(f"Teenage : {list(filter(lambda x : x["age"]<=19, people))}")

Adult : [{'name': 'Sai', 'age': 24}, {'name': 'Venkateswara', 'age': 52}]

Teenage : [{'name': 'Krishna', 'age': 18}, {'name': 'Barghav', 'age': 15}, {'name': 'Cintu', 'age': 17}]


### Random

In [30]:
import random

print(random.randint(1,25))
print(random.choice(["apple", "banana", "cherry"]))

21
apple


### Data Serialization
* json
* csv

In [31]:
import json

data = {"name" : "Sai", "age" : 24, "height" : 6.2}

# Converting to json
x = json.dumps(data)
print(x, type(x))

# Converting back json to dictionary
y = json.loads(x)
print(y, type(y))

{"name": "Sai", "age": 24, "height": 6.2} <class 'str'>
{'name': 'Sai', 'age': 24, 'height': 6.2} <class 'dict'>


In [32]:
import csv

with open("example.csv", mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["name", "age"])
    writer.writerow(["Sai Preetham", 24])

with open("example.csv", mode="r") as file:
    reader = csv.reader(file)
    for i in reader:
        print(i)

['name', 'age']
['Sai Preetham', '24']


### Date & Time
* datetime
* timedelta
* time

In [33]:
from datetime import datetime, timedelta

now = datetime.now()
print(now)

yesterday = now-timedelta(days=1)
print(yesterday)


2024-11-21 11:37:04.471800
2024-11-20 11:37:04.471800


In [34]:
import time

print(time.time())
time.sleep(2)
print(time.time())

1732169224.481039
1732169226.4821293


### Regular Expressions

In [35]:
import re

pattern = r'\d'      # d --> digit.
text = "There are 123 apples and 456 bananas."
match = re.search(pattern, text)
print(match)
print(match.group())

<re.Match object; span=(10, 11), match='1'>
1


In [36]:
import re

pattern = r'\d+'      # d+ --> digits.
text = "There are 123 apples and 456 bananas."
match = re.search(pattern, text)
print(match)
print(match.group())

<re.Match object; span=(10, 13), match='123'>
123


### File Handling
* Read mode ---> r
* Write mode ---> w
* Append mode ---> a

In [37]:
# Reading a File

with open("example.txt", "r") as file:
    content = file.read()
    print(content)

Hello, World!
The previous content is OverWritten.

This is an append mode
The previous content don't get OverWritten.


In [38]:
# Writing a File(OverWriting)

with open("example.txt", "w") as file:
    file.write("Hello, World!\n")
    file.write("The previous content is OverWritten.\n")

In [39]:
with open("example.txt", "r") as file:
    content = file.read()
    print(content)

Hello, World!
The previous content is OverWritten.



In [40]:
# Writing a File(without OverWriting)

with open("example.txt", "a") as file:
    file.write("\nThis is an append mode\n")
    file.write("The previous content don't get OverWritten.")

In [41]:
with open("example.txt", "r") as file:
    content = file.read()
    print(content)

Hello, World!
The previous content is OverWritten.

This is an append mode
The previous content don't get OverWritten.


### try, except, else and finally

In [42]:
try:
    num = 0
    res = 10/num
except ZeroDivisionError:
    print("The Denominator should be greater than 0.")
except ValueError:
    print("The input should be a number not a string.")
else:
    print(f"Result : {res}")
finally:
    print("\nExecution Completed.")

The Denominator should be greater than 0.

Execution Completed.


### Oops

In [43]:
class Students():
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def subject(self):
        print(f"{self.name} is Studying.")
    def games(self):
        print(f"{self.name} plays Games.")

s1 = Students("Sai", 24)
s2 = Students("Krishna", 22)

print(f"Name : {s1.name}, Age : {s1.age}")
print(f"Name : {s2.name}, Age : {s2.age}")
print()

s1.games()
s2.subject()

Name : Sai, Age : 24
Name : Krishna, Age : 22

Sai plays Games.
Krishna is Studying.


### Numpy

In [44]:
import  numpy as np

### 1D

In [45]:
x1 = np.array([1,2,3,4,5])
print(f"Array : {x1}")
print(f"Shape : {x1.shape}")
print(f"Dimension : {x1.ndim}")

Array : [1 2 3 4 5]
Shape : (5,)
Dimension : 1


In [46]:
x2 = np.arange(0,10)
print(f"Array : {x2}")
print(f"Shape  : {x2.shape}")
print(f"Dimension : {x2.ndim}")

Array : [0 1 2 3 4 5 6 7 8 9]
Shape  : (10,)
Dimension : 1


In [47]:
x3 = np.arange(0,10,2)
print(x3)

[0 2 4 6 8]


### 2D

In [48]:
x4 = x3.reshape(5,1)       # 5 rows and 1 column
print(f"Array : \n{x4}")
print(f"Dimension : {x4.ndim}")
print()
x5 = x3.reshape(1,5)       # 1 row and 5 columns
print(f"Array : {x5}")
print(f"Dimension : {x5.ndim}")

Array : 
[[0]
 [2]
 [4]
 [6]
 [8]]
Dimension : 2

Array : [[0 2 4 6 8]]
Dimension : 2


### ones and zeros

In [49]:
print(np.ones((3,4)))
print()
print(np.zeros((2,5)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Identity Matrix

In [50]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
arr = np.array([[1,2,3], [4,5,6]])
print("Array :\n", arr)
print("Shape : ", arr.shape)
print("Dimension : ", arr.ndim)
print("Size (no.of elements) : ", arr.size)
print("Data type : ", arr.dtype)
print("Item Size(in bytes) : ", arr.itemsize)

Array :
 [[1 2 3]
 [4 5 6]]
Shape :  (2, 3)
Dimension :  2
Size (no.of elements) :  6
Data type :  int64
Item Size(in bytes) :  8


In [52]:
arr1 = np.arange(1,6)
arr2 = np.arange(10,51,10)

print("Array 1 : ", arr1)
print("Array 2 : ", arr2)


Array 1 :  [1 2 3 4 5]
Array 2 :  [10 20 30 40 50]


### Add, Sub, Mul, Div

In [53]:
print("Addition : ", arr1+arr2)
print("Substraction : ", arr1-arr2)
print("Multiplication : ", arr1*arr2)
print("Division : ", arr1/arr2)

Addition :  [11 22 33 44 55]
Substraction :  [ -9 -18 -27 -36 -45]
Multiplication :  [ 10  40  90 160 250]
Division :  [0.1 0.1 0.1 0.1 0.1]


### Array Slicing

In [ ]:
arr1 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array :\n", arr1)

# get 7,8,11,12 elements:
print("\n", arr1[1:])            # arr1[row slicing]
print("\n", arr1[1:,2:])         # arr1[row slicing, column slicing]

Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 [[ 5  6  7  8]
 [ 9 10 11 12]]

 [[ 7  8]
 [11 12]]


In [55]:
# get 2,3,6,7
print(arr1[:2], "\n")
print(arr1[:2,1:3])

[[1 2 3 4]
 [5 6 7 8]] 

[[2 3]
 [6 7]]


In [56]:
arr1[:2,1:3].reshape(1,4)

array([[2, 3, 6, 7]])

In [57]:
arr1[:2,1:3].reshape(4,1)

array([[2],
       [3],
       [6],
       [7]])

### Mean, Median, Standard Deviation, Variance

In [58]:
data = np.arange(1,11)
print("Data : ", data)

mean = np.mean(data)
print("Mean : ", mean)

median = np.median(data)
print("Median : ", median)

std_dev = np.std(data)
print("Standard Deviation : ", std_dev)

variance = np.var(data)
print("Variance : ", variance)

Data :  [ 1  2  3  4  5  6  7  8  9 10]
Mean :  5.5
Median :  5.5
Standard Deviation :  2.8722813232690143
Variance :  8.25


In [59]:
x = np.arange(1,16)
print("Data : ", x)
print("Elements > 5 : ", x[x>5])
print("Elements > 5 and <= 10 : ", x[(x>5) & (x<=10)])

Data :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Elements > 5 :  [ 6  7  8  9 10 11 12 13 14 15]
Elements > 5 and <= 10 :  [ 6  7  8  9 10]


### Pandas

In [60]:
import pandas as pd

### Series is like 1D array in Numpy

In [61]:
data = [1,2,3,4,5]
x = pd.Series(data)
x

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [62]:
data = [1,2,3,4,5]
index = ["a", "b", "c", "d", "e"]
x = pd.Series(data,index)
x

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [63]:
dic = {"Sai" : 24, "Krishna" : 22, "Subhashini" : 44, "Venkateswara" : 52}
x = pd.Series(dic)
x

Sai             24
Krishna         22
Subhashini      44
Venkateswara    52
dtype: int64

### Data Frames is like Multi Dimensional Arrays

In [64]:
# 1st Method : using "keys"(Column Names) multiple times.

data = [{"Name" : "Sai Preetham", "Age" : 24, "Occupation" : "Software Engineer", "City" : "Bangalore"},
        {"Name" : "Barghava", "Age" : 20, "Occupation" : "B.Pharmacy", "City" : "Guntur"},
        {"Name" : "Krishna Chaitanya", "Age" : 22, "Occupation" : "M.B.B.S", "City" : "Guntur"}]

df = pd.DataFrame(data)
df

Name  Age         Occupation       City
0       Sai Preetham   24  Software Engineer  Bangalore
1           Barghava   20         B.Pharmacy     Guntur
2  Krishna Chaitanya   22            M.B.B.S     Guntur

In [65]:
# 2nd Method : using "keys"(Column Names) only 1 time.

data = {"Name" : ["Sai Preetham", "Krishna Chaitanya", "Barghava"],
        "Age" : [24, 22, 20],
        "Occupation" : ["Software Engineer", "M.B.B.S", "B.Pharmacy"],
        "City" : ["Bangalore", "Guntur", "Guntur"]}

df = pd.DataFrame(data)
df

Name  Age         Occupation       City
0       Sai Preetham   24  Software Engineer  Bangalore
1  Krishna Chaitanya   22            M.B.B.S     Guntur
2           Barghava   20         B.Pharmacy     Guntur

### Data Frames to Numpy

In [66]:
np.array(df)

array([['Sai Preetham', 24, 'Software Engineer', 'Bangalore'],
       ['Krishna Chaitanya', 22, 'M.B.B.S', 'Guntur'],
       ['Barghava', 20, 'B.Pharmacy', 'Guntur']], dtype=object)

### Reading a csv file

In [67]:
hulu_df = pd.read_csv("datasets/hulu_data_set.csv")
hulu_df.head()

title   type                     genres  releaseYear  \
0                Ariel  movie     Comedy, Crime, Romance       1988.0   
1  Shadows in Paradise  movie       Comedy, Drama, Music       1986.0   
2         Forrest Gump  movie             Drama, Romance       1994.0   
3    The Fifth Element  movie  Action, Adventure, Sci-Fi       1997.0   
4   My Life Without Me  movie             Drama, Romance       2003.0   

      imdbId  imdbAverageRating  imdbNumVotes availableCountries  
0  tt0094675                7.4        8776.0                 JP  
1  tt0092149                7.5        7538.0                 JP  
2  tt0109830                8.8     2320505.0                 JP  
3  tt0119116                7.6      517631.0                 JP  
4  tt0314412                7.4       26044.0                 JP

### loc & iloc
* Accessing particular rows.

In [68]:
data = {"Name" : ["Sai Preetham", "Krishna Chaitanya", "Barghava"],
        "Age" : [24, 22, 20],
        "Occupation" : ["Software Engineer", "M.B.B.S", "B.Pharmacy"],
        "City" : ["Bangalore", "Guntur", "Guntur"]}
index = ["a", "b", "c"]

df = pd.DataFrame(data, index)
df

Name  Age         Occupation       City
a       Sai Preetham   24  Software Engineer  Bangalore
b  Krishna Chaitanya   22            M.B.B.S     Guntur
c           Barghava   20         B.Pharmacy     Guntur

In [69]:
# loc ---> location
print(df.loc["b"])

Name          Krishna Chaitanya
Age                          22
Occupation              M.B.B.S
City                     Guntur
Name: b, dtype: object


In [70]:
# iloc ---> integer-based location
df.iloc[0]

Name               Sai Preetham
Age                          24
Occupation    Software Engineer
City                  Bangalore
Name: a, dtype: object

### at & iat
* Accessing particular element.

In [71]:
df

Name  Age         Occupation       City
a       Sai Preetham   24  Software Engineer  Bangalore
b  Krishna Chaitanya   22            M.B.B.S     Guntur
c           Barghava   20         B.Pharmacy     Guntur

In [72]:
df.loc["b"]

Name          Krishna Chaitanya
Age                          22
Occupation              M.B.B.S
City                     Guntur
Name: b, dtype: object

In [73]:
# using index(row) name and column name for getting a particular element.
print(df.at["b","Age"])

22


In [74]:
df

Name  Age         Occupation       City
a       Sai Preetham   24  Software Engineer  Bangalore
b  Krishna Chaitanya   22            M.B.B.S     Guntur
c           Barghava   20         B.Pharmacy     Guntur

In [75]:
df.iloc[2]

Name            Barghava
Age                   20
Occupation    B.Pharmacy
City              Guntur
Name: c, dtype: object

In [76]:
# using row number and column number for getting a particular element.
print(df.iat[2,0])

Barghava


### Data Manipulation

In [77]:
df

Name  Age         Occupation       City
a       Sai Preetham   24  Software Engineer  Bangalore
b  Krishna Chaitanya   22            M.B.B.S     Guntur
c           Barghava   20         B.Pharmacy     Guntur

### Adding and Deleting Column

In [78]:
df["Salary"] = [30000, 5000, 0]
print(df, "\n")
df = df.drop("Salary", axis=1)      # axis=0 ---> row, axis=1 ---> column, by default axis=0
print(df)

                Name  Age         Occupation       City  Salary
a       Sai Preetham   24  Software Engineer  Bangalore   30000
b  Krishna Chaitanya   22            M.B.B.S     Guntur    5000
c           Barghava   20         B.Pharmacy     Guntur       0 

                Name  Age         Occupation       City
a       Sai Preetham   24  Software Engineer  Bangalore
b  Krishna Chaitanya   22            M.B.B.S     Guntur
c           Barghava   20         B.Pharmacy     Guntur


### Adding and Deleting Row

In [79]:
df

Name  Age         Occupation       City
a       Sai Preetham   24  Software Engineer  Bangalore
b  Krishna Chaitanya   22            M.B.B.S     Guntur
c           Barghava   20         B.Pharmacy     Guntur

In [80]:
len(df)

3

In [81]:
df.loc[len(df)] = ["Cintu", 21, "M.Tech", "Guntur"]
df

Name  Age         Occupation       City
a       Sai Preetham   24  Software Engineer  Bangalore
b  Krishna Chaitanya   22            M.B.B.S     Guntur
c           Barghava   20         B.Pharmacy     Guntur
3              Cintu   21             M.Tech     Guntur

### Changing index number "3" to "d"

In [82]:
df = df.rename(index={3 : "d"})
df

Name  Age         Occupation       City
a       Sai Preetham   24  Software Engineer  Bangalore
b  Krishna Chaitanya   22            M.B.B.S     Guntur
c           Barghava   20         B.Pharmacy     Guntur
d              Cintu   21             M.Tech     Guntur

In [83]:
df = df.drop("d")   # by default axis = 0.
df

Name  Age         Occupation       City
a       Sai Preetham   24  Software Engineer  Bangalore
b  Krishna Chaitanya   22            M.B.B.S     Guntur
c           Barghava   20         B.Pharmacy     Guntur

### Statistical Data from a Data Frame

In [84]:
df.describe()

Age
count   3.0
mean   22.0
std     2.0
min    20.0
25%    21.0
50%    22.0
75%    23.0
max    24.0