In [1]:
import random
import numpy as np
import pandas as pd

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
x = np.empty((5,5))
x = [[random.randint(2,19) for j in range(5)] for i in range(5)]
x = np.array(x)
print(f"Original Array : \n{x}\n")
for i in range(5):
    x[i][2] = 1
print(f"3rd column elements replaced with 1 : \n{x}\n")

Original Array : 
[[18  4 16 14  7]
 [14  8  8 14 11]
 [11  8 16  4  7]
 [ 2 18 19  5  2]
 [17 11 16 18  6]]

3rd column elements replaced with 1 : 
[[18  4  1 14  7]
 [14  8  1 14 11]
 [11  8  1  4  7]
 [ 2 18  1  5  2]
 [17 11  1 18  6]]



In [3]:
y = np.empty((4,4))
y = [[random.randint(2,20) for j in range(4)] for i in range(4)]
y = np.array(y)
print(f"Original Array : \n{y}\n")
for i in range(4):
    y[i][i] = 0
print(f"Diagonal elements replaced with 0 : \n{y}")

Original Array : 
[[ 3  9 13 17]
 [18  8  2  7]
 [ 2 16  9 10]
 [ 6 10 17 20]]

Diagonal elements replaced with 0 : 
[[ 0  9 13 17]
 [18  0  2  7]
 [ 2 16  0 10]
 [ 6 10 17  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [4]:
x = np.empty((6,6))
x = [[random.randint(1,36) for j in range(5)] for i in range(5)]
x = np.array(x)
print(f"Original Array : \n{x}\n")
print(f"Sub Array containing rows from 3 to 5 : \n{x[2:]}\n")
print(f"Sub Array containing columns from 2 to 4 : \n{x[:,1:4]}")

Original Array : 
[[28 36 30 35 23]
 [22 32 28  6 34]
 [32 17 12 28 21]
 [11 35 34 35  7]
 [36 15  3 30 15]]

Sub Array containing rows from 3 to 5 : 
[[32 17 12 28 21]
 [11 35 34 35  7]
 [36 15  3 30 15]]

Sub Array containing columns from 2 to 4 : 
[[36 30 35]
 [32 28  6]
 [17 12 28]
 [35 34 35]
 [15  3 30]]


In [5]:
y = np.empty((5,5))
y = [[random.randint(1,36) for j in range(5)] for i in range(5)]
y = np.array(y)
print(f"Original Array : \n{y}\n")
row,col = y.shape
print(f"Border Elements : {[int(y[0][0]), int(y[0][col-1]), int(y[row-1][0]), int(y[row-1][col-1])]}")

Original Array : 
[[29 36 23 28 19]
 [ 5 18  1 34 25]
 [32 18 22 28 29]
 [36 16 13 13 26]
 [36 31 32  4 14]]

Border Elements : [29, 19, 36, 14]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [6]:
x = np.empty((3,4))
x = [[random.randint(1,100) for j in range(4)] for i in range(3)]
x = np.array(x)
print(f"Array 1:\n{x}\n")

y = np.empty((3,4))
y = [[random.randint(1,100) for j in range(4)] for i in range(3)]
y = np.array(y)
print(f"Array 2 :\n{y}\n")

print(f"Addition of 2 Arrays : \n{x+y}\n")
print(f"Subtraction of 2 Arrays : \n{x-y}\n")
print(f"Multiplication of 2 Arrays : \n{x*y}\n")
print(f"Division of 2 Arrays : \n{x/y}")

Array 1:
[[93 24 77 14]
 [65 90 50 66]
 [74 73 41 65]]

Array 2 :
[[71 33 33 82]
 [16  8 11 95]
 [89 31 91 80]]

Addition of 2 Arrays : 
[[164  57 110  96]
 [ 81  98  61 161]
 [163 104 132 145]]

Subtraction of 2 Arrays : 
[[ 22  -9  44 -68]
 [ 49  82  39 -29]
 [-15  42 -50 -15]]

Multiplication of 2 Arrays : 
[[6603  792 2541 1148]
 [1040  720  550 6270]
 [6586 2263 3731 5200]]

Division of 2 Arrays : 
[[ 1.30985915  0.72727273  2.33333333  0.17073171]
 [ 4.0625     11.25        4.54545455  0.69473684]
 [ 0.83146067  2.35483871  0.45054945  0.8125    ]]


In [7]:
x = np.empty((4,4))
x = [[random.randint(1,16) for j in range(4)] for i in range(4)]
x = np.array(x)
print(f"Array :\n{x}\n")

row_sum = np.sum(x, axis=1)
col_sum = np.sum(x, axis=0)

print(f"Row-wise Sum : {row_sum}")
print(f"Column-wse Sum : {col_sum}")


Array :
[[ 2 13 10 11]
 [ 6  9  9  5]
 [15  6  5  1]
 [16  1  8  2]]

Row-wise Sum : [36 29 27 27]
Column-wse Sum : [39 29 32 19]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [8]:
x = np.empty((5,5))
x = [[random.randint(1,100) for j in range(5)] for i in range(5)]
x = np.array(x)
print(f"Array :\n{x}\n")

print(f"Mean : {np.mean(x)}")
print(f"Median : {np.median(x)}")
print(f"Standard Deviation : {np.std(x)}")
print(f"Variance : {np.var(x)}")

Array :
[[14  4 14 80 85]
 [21 96 55 26 57]
 [56 42 95 14 21]
 [ 6 23 54 13 47]
 [61 20 71 98 99]]

Mean : 46.88
Median : 47.0
Standard Deviation : 31.422692437154392
Variance : 987.3856


In [9]:
y = np.empty((3,3))
y = [[random.randint(1,9) for j in range(3)] for i in range(3)]
y = np.array(y)
print(f"Array : \n{y}\n")

norm = (y-np.mean(y))/np.std(y)
print(f"Normalization :\n{norm}")

Array : 
[[7 4 3]
 [4 7 8]
 [3 5 4]]

Normalization :
[[ 1.13389342 -0.56694671 -1.13389342]
 [-0.56694671  1.13389342  1.70084013]
 [-1.13389342  0.         -0.56694671]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [25]:
x = np.random.randint(1,100, size=(3,3))
y = np.random.randint(1,100, size=(3))
print(f"2D Array : \n{x}\n\n1D Array : \n{y}\n")

print(f"Adding 1D array to each row of 2D Array : \n{x+y}")

2D Array : 
[[57 77 35]
 [85 12 22]
 [18 23 77]]

1D Array : 
[98 60 58]

Adding 1D array to each row of 2D Array : 
[[155 137  93]
 [183  72  80]
 [116  83 135]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.